#===== You can edit your configuration in this 'substitution' section =====#
substitutions:
  device_name: "garage-links"  # only lowercase, numbers, - and _ allowed!
  friendly_name: "Garage links"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  local_domain: ".fritz.box"
  hotspot_password: !secret hotspot_password
  ota_password: !secret ota_password
  api_encryption_key: !secret api_encryption

  open_duration: 16.5s
  close_duration: 17.5s

##### Changes beyond this line may break the functionality #####

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp8266:
  board: d1_mini

status_led:
  pin: GPIO2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ${api_encryption_key}

ota:
  - platform: esphome
    password: ${ota_password}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  domain: ${local_domain}
  use_address: 192.168.178.159

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}
    password: ${hotspot_password}

captive_portal:
    

output:
  - platform: gpio
    pin: 
      number: GPIO15
    id: gpio_impulse

button:
  - platform: output
    id: open_close_impulse
    output: gpio_impulse
    duration: 300ms

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${friendly_name} Button"
    id: external_button
    disabled_by_default: true
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_press:
      then:
        - button.press: open_close_impulse

  - platform: gpio
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true
      inverted: true
    id: is_opened
    name: "${friendly_name} open"
    disabled_by_default: true
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms

  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    id: is_closed
    name: "${friendly_name} closed"
    disabled_by_default: true
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms

  - platform: gpio
    pin:
      number: GPIO12
      mode:
        input: true
        pullup: true
    id: motor_opening
    name: "${friendly_name} opening"
    disabled_by_default: true
    filters:
      - delayed_on: 50ms
      - delayed_off: 3000ms
      # the voltage of the motor drops at the end to slow down the garage door
      # which turns off the motor_opening detection and puts the cover in a 
      # false idle state. The delayed_off time should compensate this behaviour.

  - platform: gpio
    pin:
      number: GPIO13
      mode:
        input: true
        pullup: true
    id: motor_closing
    name: "${friendly_name} closing"
    disabled_by_default: true
    filters:
      - delayed_on: 50ms
      - delayed_off: 3300ms
      # the voltage of the motor drops at the end to slow down the garage door
      # which turns off the motor_opening detection and puts the cover in a 
      # false idle state. The delayed_off time should compensate this behaviour.

cover:
  - platform: feedback
    name: ${friendly_name}
    device_class: garage
    icon: "mdi:garage"
    
    has_built_in_endstop: true
    direction_change_wait_time: 500ms

    open_action:
      - button.press: open_close_impulse
    open_duration: ${open_duration}
    open_endstop: is_opened
    open_sensor: motor_opening

    close_action:
      - button.press: open_close_impulse
    close_duration: ${close_duration}
    close_endstop: is_closed
    close_sensor: motor_closing

    stop_action:
      - button.press: open_close_impulse
